#!/usr/bin/php
<?php

	include('parsing.php');
	include('reduce.php');
	include('delta.php');
	include('solve.php');
	include('error.php');

	if ($argc == 2)
	{
		$eq = parsing($argv[1]);
		if ($eq['degree'] == 1 || $eq['degree'] == 2)
			$eq = print_reduce($eq);
		if ($eq['degree'] == 2)
			$eq = get_delta($eq);

		if ($eq['degree'] == 0)
			errors(1);
		else if ($eq['degree'] == 1)
			solve_deg1($eq);
		else if ($eq['degree'] == 2)
			solve_deg2($eq);
		else
			errors(4);
	}
	else if ($argc == 1)
			errors(2);
	else
			errors(3);

?>
